CREATE TABLE IF NOT EXISTS COLOR_TYPE (
    ID IDENTITY NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS COLOR (
    ID IDENTITY NOT NULL PRIMARY KEY,
    LABEL VARCHAR(100) NOT NULL,
    COLOR_VALUE NUMBER,
    TYPE_ID NUMBER,
    FOREIGN KEY (TYPE_ID) REFERENCES COLOR_TYPE(ID)
);

INSERT INTO COLOR_TYPE(NAME) VALUES ('RGB');
INSERT INTO COLOR(LABEL, COLOR_VALUE, TYPE_ID) VALUES ('R', 0, 1), ('G', 0, 1), ('B', 0, 1);